#' Simulate ordinal item scores from a latent variable model
#'
#' Generates continuous and ordinal item scores from a latent variable model with
#' one or more latent factors. The function supports primary loadings,
#' cross-loadings, correlated latent variables, skewed latent variables, and
#' correlated residuals. It is mainly intended for simulation studies,
#' demonstrations.
#'
#' @param N Number of observations to generate.
#' @param seeds Random seed used for reproducibility.
#' @param nfactors Number of latent factors.
#' @param nitems Number of items per factor. Either a scalar, recycled across
#'   factors, or a vector of length `nfactors`.
#' @param loadings A list of loading matrices, one per factor. Each element
#'   should be a matrix with `nfactors` rows and `nitems[f]` columns. Rows
#'   represent latent factors and columns represent items. Cross-loadings can be
#'   specified by non-zero off-factor entries.
#' @param intercepts Item intercepts. Can be a scalar, a vector of length
#'   `nfactors`, or a list of length `nfactors` containing scalars or item-level
#'   vectors.
#' @param residuals Residual variance or covariance specification. Can be `NA`
#'   for independent residuals with variance 1, a scalar residual variance, a
#'   vector of residual variances per factor or per item, a list of residual
#'   variances per factor, or a full residual covariance matrix. A full matrix can
#'   be used to generate residual covariances between items.
#' @param threshold Threshold value(s) used to discretize continuous item scores
#'   into ordinal item scores. A scalar threshold creates two categories coded
#'   `0` and `1`; a vector of thresholds creates `length(threshold) + 1`
#'   categories coded from `0` to `length(threshold)`.
#' @param latents Optional matrix of latent factor scores. If supplied, these are
#'   used instead of generating new latent scores.
#' @param latcor Latent factor correlation specification. Use scalar `0` for
#'   independent factors, or provide a full `nfactors` by `nfactors` correlation
#'   matrix.
#' @param latskew Skewness parameter(s) used when generating skewed latent
#'   variables. Can be scalar or a vector of length `nfactors`.
#' @param latkurt Kurtosis parameter(s) used when generating non-normal latent
#'   variables with `monte1()`. Can be scalar or a vector of length `nfactors`.
#' @param skew_multivar Logical. If `TRUE` and `nfactors > 1`, the function tries
#'   to use `monte1()` to generate multivariate non-normal latent variables with
#'   the requested skewness, kurtosis, and latent correlation structure. If
#'   `FALSE`, multivariate normal latent variables are generated.
#' @param plots Logical. If `TRUE`, histograms and scatterplot matrices are
#'   produced for the generated latent variables and item scores.
#'
#' @return A list with four elements:
#' \describe{
#'   \item{Ordinal}{A list of data frames containing the generated ordinal item
#'   scores for each factor.}
#'   \item{Continuous}{A list of matrices containing the underlying continuous
#'   item scores for each factor.}
#'   \item{Latents}{A matrix containing the generated or supplied latent factor
#'   scores.}
#'   \item{Sigma_e}{The residual covariance matrix used to generate residuals.}
#' }
#'
#' @details
#' The continuous item scores are generated as
#'
#' \deqn{x = \nu + \Lambda \eta + \epsilon,}
#'
#' where `intercepts` define \eqn{\nu}, `loadings` define \eqn{\Lambda},
#' `latents` or generated factor scores define \eqn{\eta}, and `residuals`
#' define the residual covariance matrix of \eqn{\epsilon}. Ordinal scores are
#' then obtained by applying `findInterval()` to the continuous item scores using
#' the supplied thresholds.
#'
#' Skewed ordinal item distributions can be generated by using asymmetric
#' thresholds, skewed latent variables, or both.
#'
#' @note
#' This function uses `mvtnorm`, `MASS`, `fungible`, and `sn`. For package
#' development, these should preferably be declared in `DESCRIPTION` under
#' `Imports`, and functions should be called with explicit namespaces rather than
#' using `require()` inside the function.
#'
#' @examples
#' ## One-factor model with five ordinal items
#' load1 <- matrix(rep(.80, 5), nrow = 1)
#'
#' sim1 <- ordskew(
#'   N = 500,
#'   seeds = 123,
#'   nfactors = 1,
#'   nitems = 5,
#'   loadings = list(load1),
#'   residuals = .36,
#'   threshold = c(-1.5, -0.5, 0.5, 1.5),
#'   plots = FALSE
#' )
#'
#' head(sim1$Ordinal[[1]])
#'
#' ## Two correlated factors with one cross-loading
#' loadA <- matrix(
#'   c(
#'     .80, .80, .80, .80,
#'     0,   0,   0,   .30
#'   ),
#'   nrow = 2,
#'   byrow = TRUE
#' )
#'
#' loadB <- matrix(
#'   c(
#'     .30, 0,   0,   0,
#'     .80, .80, .80, .80
#'   ),
#'   nrow = 2,
#'   byrow = TRUE
#' )
#'
#' sim2 <- ordskew(
#'   N = 500,
#'   seeds = 123,
#'   nfactors = 2,
#'   nitems = c(4, 4),
#'   loadings = list(loadA, loadB),
#'   residuals = .36,
#'   threshold = c(-1.5, -0.5, 0.5, 1.5),
#'   latcor = matrix(c(1, .30, .30, 1), 2, 2),
#'   skew_multivar = FALSE,
#'   plots = FALSE
#' )
#'
#' cor(rowSums(sim2$Ordinal[[1]]), rowSums(sim2$Ordinal[[2]]))
#'
#' @export
sim_items_lvm <- function(
    N, seeds, nfactors, nitems, loadings,
    intercepts = 0,
    residuals  = NA,
    threshold  = 0,
    latents    = NA,
    latcor     = 0,
    latskew    = 0,
    latkurt    = 0,
    skew_multivar = TRUE,   # if TRUE and nfactors>1, try monte1()
    plots      = TRUE
) {

  set.seed(seeds)

  # ---- Ensure nitems ----
  if (length(nitems) != nfactors) nitems <- rep(nitems, nfactors)
  p_total <- sum(nitems)

  # ---- Intercepts: FIXED bug (use 'intercepts' consistently) ----
  # Accept scalar, vector per factor, or list per factor
  intercept <- NULL
  if (is.list(intercepts)) {
    if (length(intercepts) != nfactors) {
      stop("ERROR: if 'intercepts' is a list, it must have length nfactors.")
    }
    intercept <- lapply(1:nfactors, function(f) {
      x <- intercepts[[f]]
      if (length(x) == 1) rep(x, nitems[f])
      else if (length(x) == nitems[f]) x
      else stop("ERROR: intercepts[[", f, "]] must be scalar or length nitems[f].")
    })
  } else {
    # numeric scalar or vector
    if (length(intercepts) == 1) {
      intercept <- lapply(1:nfactors, function(f) rep(intercepts, nitems[f]))
    } else if (length(intercepts) == nfactors) {
      intercept <- lapply(1:nfactors, function(f) rep(intercepts[f], nitems[f]))
    } else {
      stop("ERROR: 'intercepts' must be a scalar, a length-nfactors vector, or a list of length nfactors.")
    }
  }

  # ---- Latent correlation specification ----
  if (is.numeric(latcor) && length(latcor) == 1 && latcor == 0) {
    lvcor <- diag(nfactors)
  } else if (is.matrix(latcor)) {
    if (!all(dim(latcor) == c(nfactors, nfactors))) {
      stop("ERROR: 'latcor' must be a ", nfactors, "x", nfactors, " correlation matrix when nfactors > 1.")
    }
    if (!isTRUE(all.equal(latcor, t(latcor), tolerance = 1e-10))) {
      stop("ERROR: 'latcor' correlation matrix is not symmetric.")
    }
    if (any(abs(diag(latcor) - 1) > 1e-10)) {
      stop("ERROR: diagonal of 'latcor' must contain 1's.")
    }
    if (any(eigen(latcor, symmetric = TRUE)$values <= 0)) {
      stop("ERROR: 'latcor' correlation matrix is not positive definite.")
    }
    lvcor <- latcor
  } else if (is.numeric(latcor) && length(latcor) == 1 && latcor != 0) {
    stop("ERROR: When nfactors > 1 and latent correlations are non-zero, 'latcor' must be a full correlation matrix.")
  } else {
    stop("ERROR: Invalid 'latcor' specification. Use 0 (scalar) for independent factors or a full correlation matrix.")
  }

  # ---- Generate latent variables (optionally skewed multivariate) ----
  if (all(is.na(latents))) {

    if (nfactors > 1) {
      # Always use multivariate normal
      theta <- MASS::mvrnorm(
        n = N,
        mu = rep(0, nfactors),
        Sigma = lvcor
      )
    } else {
      # Keep skew for single factor (this still works via 'sn')
      theta <- as.vector(
        sn::rsn(n = N, xi = 0, omega = 1, alpha = latskew)
      )
      theta <- as.matrix(theta)
    }

  } else {
    theta <- as.matrix(latents)
  }

  # ---- Residual handling: build Sigma_e from multiple input formats ----
  build_Sigma_e <- function(residuals, nitems) {
    p_total <- sum(nitems)

    # Default: variance 1, independent
    if (all(is.na(residuals))) {
      return(diag(rep(1, p_total)))
    }

    # Full covariance matrix
    if (is.matrix(residuals)) {
      if (!all(dim(residuals) == c(p_total, p_total))) {
        stop("ERROR: 'residuals' matrix must be ", p_total, "x", p_total, ".")
      }
      if (!isTRUE(all.equal(residuals, t(residuals), tolerance = 1e-10))) {
        stop("ERROR: 'residuals' covariance matrix is not symmetric.")
      }
      if (any(diag(residuals) <= 0)) {
        stop("ERROR: diagonal of 'residuals' must contain positive residual variances.")
      }
      if (any(eigen(residuals, symmetric = TRUE)$values <= 0)) {
        stop("ERROR: 'residuals' covariance matrix is not positive definite.")
      }
      return(residuals)
    }

    # Numeric scalar or vector or list
    if (is.list(residuals)) {
      if (length(residuals) != length(nitems)) {
        stop("ERROR: if 'residuals' is a list, it must have length nfactors.")
      }
      vars <- unlist(lapply(seq_along(nitems), function(f) {
        r <- residuals[[f]]
        if (!is.numeric(r)) stop("ERROR: residuals[[", f, "]] must be numeric.")
        if (length(r) == 1) rep(r, nitems[f])
        else if (length(r) == nitems[f]) r
        else stop("ERROR: residuals[[", f, "]] must be scalar or length nitems[f].")
      }))
      if (any(vars <= 0)) stop("ERROR: residual variances must be > 0.")
      return(diag(vars))
    }

    if (!is.numeric(residuals)) {
      stop("ERROR: 'residuals' must be NA, numeric, list, or a covariance matrix.")
    }

    # numeric scalar
    if (length(residuals) == 1) {
      if (residuals <= 0) stop("ERROR: residual variance must be > 0.")
      return(diag(rep(residuals, p_total)))
    }

    # numeric vector: either per-factor or per-item
    if (length(residuals) == length(nitems)) {
      if (any(residuals <= 0)) stop("ERROR: residual variances must be > 0.")
      vars <- unlist(mapply(function(v, ni) rep(v, ni), residuals, nitems))
      return(diag(vars))
    }

    if (length(residuals) == p_total) {
      if (any(residuals <= 0)) stop("ERROR: residual variances must be > 0.")
      return(diag(residuals))
    }

    # nfactors==1 convenience: vector length nitems[1]
    if (length(nitems) == 1 && length(residuals) == nitems[1]) {
      if (any(residuals <= 0)) stop("ERROR: residual variances must be > 0.")
      return(diag(residuals))
    }

    stop(
      "ERROR: numeric 'residuals' must be: scalar, length nfactors, length p_total, ",
      "or (if nfactors==1) length nitems[1]; or provide a list (length nfactors) or full covariance matrix."
    )
  }

  Sigma_e <- build_Sigma_e(residuals, nitems)

  # Draw residuals (global)
  errors_all <- MASS::mvrnorm(n = N, mu = rep(0, p_total), Sigma = Sigma_e)

  # ---- Generate continuous item scores with cross-loadings (vectorized) ----
  contscores <- vector("list", nfactors)

  col_start <- 1L
  for (f in 1:nfactors) {
    n_it <- nitems[f]
    col_end <- col_start + n_it - 1L

    # eta = theta %*% loadings[[f]]  (N x nfactors) %*% (nfactors x n_it) = N x n_it
    eta <- theta %*% loadings[[f]]

    # add intercepts (recycled across rows) + residual slice
    contscores[[f]] <- sweep(eta, 2, intercept[[f]], FUN = "+") +
      errors_all[, col_start:col_end, drop = FALSE]

    col_start <- col_end + 1L
  }

  # ---- Convert to ordinal items (fast + consistent) ----
  # Uses findInterval:
  # - if threshold scalar: returns 0/1
  # - if thresholds length K: returns 0..K
  ordscores <- lapply(contscores, function(mat) {
    out <- as.data.frame(mat)
    for (j in seq_len(ncol(out))) {
      out[[j]] <- findInterval(out[[j]], vec = threshold)
      names(out)[j] <- paste0("x", j)
    }
    out
  })

  # ---- Plots (optional) ----
  if (plots) {
    for (f in 1:nfactors) {
      hist(theta[, f], breaks = 30, main = paste0("Factor ", f), xlab = "Latent score")
    }
    for (f in 1:nfactors) pairs(contscores[[f]])
    for (f in 1:nfactors) pairs(ordscores[[f]])
  }

  return(list(
    Ordinal    = ordscores,
    Continuous = contscores,
    Latents    = theta,
    Sigma_e    = Sigma_e
  ))
}

